apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "taskmaster.fullname" . }}-config
  labels:
    {{- include "taskmaster.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.config.appEnv | quote }}
  BACKEND_SERVICE_URL: {{ .Values.config.backendServiceUrl | quote }}
